// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for UserPoolClientSecretFunction
 */
export interface UserPoolClientSecretFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/user-pool-client-secret.
 */
export class UserPoolClientSecretFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: UserPoolClientSecretFunctionProps) {
    super(scope, id, {
      description: 'src/user-pool-client-secret.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/user-pool-client-secret.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}